latin_numbers = ["primus", "secundus", "tertius", "quartus", "quintus", "sextus", "septimus", "octavus", "nonus", "decimus"]
alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
characteristics_list = [
    "immune-strong",
    "immune-weak",
    "thick-skin",
    "thin-skin",
    "birth-egg",
    "birth-live",
    "reproduce-a",
    "reproduce-s",
    "skin-dark",
    "skin-light",
    "vision-monocular",
    "vision-bimonocular",
    "vision-colour",
    "diet-carnivore",
    "diet-omnivore",
    "diet-herbivore",
    "movement-wings",
    "movement-flight",
    "movement-fast",
    "movement-agile",
    "movement-slow",
    "breathe-underwater",
    "breathe-land",
    "large-ears",
    "medium-ears",
    "small-ears",
    "large-feet",
    "medium-feet",
    "small-feet",
    "large-nose",
    "medium-nose",
    "small-nose",
    "size-large",
    "size-medium",
    "size-small"

]